name: Hello World
run-name: ${{ github.actor }} is helloing the world
on:
  - push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!!!1!"
      - run: make hello
