name: Hello World
run-name: ${{ github.actor }} is helloing the world
on:
  - push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!!!1!"
      - uses: actions/checkout@main
      - run: pwd; ls
      - run: ls ${{ github.workspace }}
      - run: make hello
      - run: ./spin

  # build-badge:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Building badge…"
  #     - name: Build-A-Badge
  #       uses: peterrhodesdev/build-a-badge@v1.3.1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         filename: ("coverage" "idk")
  #         label: ("Coverage" "Idk")
  #         message: ("100%, yee haaw 🤠" "...")
  #         color: ("4078c0" "4078c0")
