name: Hello World
run-name: ${{ github.actor }} is helloing the world
on:
  - push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!!!1!"
      - uses: actions/checkout@main
      - run: pwd; ls
      - run: ls ${{ github.workspace }}
      - run: make hello
      - run: ./spin
  try-coverage:
    runs-on: ubuntu-latest
        steps:
          - run: echo "Hello world!!!1!"
          - run: lcov
